# Generated by Django 5.2.15 on 2026-06-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="accounts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("acName", models.CharField(max_length=50)),
                ("acNum", models.IntegerField()),
                ("acType", models.CharField(max_length=50)),
                ("bal", models.FloatField()),
                ("pin", models.IntegerField()),
            ],
        ),
    ]
