# Generated by Django 5.2.15 on 2026-07-01 05:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField(null=True)),
                ("dob", models.DateField(null=True)),
                ("course", models.CharField(max_length=100)),
                ("yop", models.IntegerField(null=True)),
            ],
        ),
    ]
